module.exports = {
  apps: [
    {
      name: 'iqbot-v2-bot',
      script: 'main_bot.py',
      interpreter: 'python3',
      cwd: '/root/iqbot-v2',
      autorestart: true,
      restart_delay: 3000,
      max_memory_restart: '500M',
      out_file: '/root/iqbot-v2/logs/bot-out.log',
      error_file: '/root/iqbot-v2/logs/bot-error.log',
      env: { NODE_ENV: 'production' },
    },
    {
      name: 'iqbot-v2-bias',
      script: 'main_bias.py',
      interpreter: 'python3',
      cwd: '/root/iqbot-v2',
      autorestart: true,
      restart_delay: 5000,
      max_memory_restart: '500M',
      out_file: '/root/iqbot-v2/logs/bias-out.log',
      error_file: '/root/iqbot-v2/logs/bias-error.log',
    },
    {
      name: 'iqbot-v2-affiliate-listener',
      script: 'utils/affiliate_listener.py',
      interpreter: 'python3',
      cwd: '/root/iqbot-v2',
      autorestart: true,
      restart_delay: 5000,
      out_file: '/root/iqbot-v2/logs/affiliate-out.log',
      error_file: '/root/iqbot-v2/logs/affiliate-error.log',
    },
    {
      name: 'iq-trader',
      script: 'server.js',
      cwd: '/root/iqbot-v2/iq-trader',
      autorestart: true,
      restart_delay: 3000,
      max_memory_restart: '300M',
      out_file: '/root/iqbot-v2/logs/iq-trader-out.log',
      error_file: '/root/iqbot-v2/logs/iq-trader-error.log',
      env: {
        NODE_ENV: 'production',
        PORT: '3001',
      },
    },
  ]
};
